name: dog_slider
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../_shared/

  flare_flutter: ^3.0.2
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - packages/dog_slider/assets/DogAnimation.flr
    - images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
