name: bubble_tab_bar
description: Example of a custom nav bar that changes the size of it's buttons when selected

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared:
    path: ../_shared/

  cupertino_icons: ^1.0.2
  outline_material_icons:
    path: ../../../outline_material_icons

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
